code_map = {
    0x104: "engine_load",
    0x105: "engine_coolant_temperature",
    0x10a: "fuel_pressure",
    0x10b: "intake_manifold_pressure",
    0x10c: "engine_rpm",
    0x10d: "vehicle_speed",
    0x10e: "timing_advance",
    0x10f: "intake_air_temperature",
    0x110: "maf_air_flow",
    0x111: "throttle_position",
    0x11f: "run_time",
    0x121: "distance_with_malfunction_light",
    0x12f: "fuel_level_input",
    0x131: "distance_since_codes_cleared",
    0x133: "barometric_pressure",
    0x142: "control_module_voltage",
    0x143: "absolute_load",
    0x15b: "hybrid_battery_remaining_life",
    0x15c: "engine_oil_temperature",
    0x15e: "engine_fuel_rate",
    0x11: "utc_date",
    0x10: "utc_time",
    0xA: "latitude",
    0xB: "longitude",
    0xC: "altitude",
    0xD: "speed",
    0xE: "course",
    0xF: "satellite_number",
    0x20: ['accelerometer_x', 'accelerometer_y', 'accelerometer_z'],
    0x21: ['gyroscope_x', 'gyroscope_y', 'gyroscope_z'],
    0x22: ['magitude_x', 'magitude_y', 'magitude_z'],
    0x23: "mems_temperature",
    0x24: "battery_voltage",
    0x25: "orientation",
    0x30: "trip_distance",
    0x81: "cellular_signal_level",
    0x82: "cpu_temperature",
    0x83: "cpu_hall",
    0: "timestamp"
}
